*<h1> <b>Stock Data Extraction Using WebScraping*<b></h1>

We will be using <code>WebScraping</code> to obtain financial data from a web-page

In [2]:
#!pip install pandas==1.3.3
#!pip install requests==2.26.0
!mamba install bs4==4.10.0-y
!mamba install html5lib==1.1-y 
!pip install lxml==4.6.4
#!pip install plotly==5.3.1

0 examples ran in 0.0000 seconds


0 examples ran in 0.0000 seconds
Requirement already satisfied: lxml==4.6.4 in c:\users\navob\appdata\local\programs\python\python310\lib\site-packages (4.6.4)

In [1]:
import pandas as pd
import requests
from bs4 import BeautifulSoup

## Using the <code>WebScraping</code> to Extract Stock Data

 We will extract Netflix stock data [https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0220EN-SkillsNetwork/labs/project/netflix_data_webpage.html](https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0220EN-SkillsNetwork/labs/project/netflix_data_webpage.html).<br>We are using Request library for sending an HTTP request to the webpage.<br>

In [2]:
url = "https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0220EN-SkillsNetwork/labs/project/netflix_data_webpage.html"
data  = requests.get(url).text

Parse the text into html using BeautifulSoup()

In [3]:
soup = BeautifulSoup(data, 'html5lib')

Turning the html table into a pandas dataframe

In [4]:
netflix_data = pd.DataFrame(columns=["Date", "Open", "High", "Low", "Close", "Volume"])

In [5]:
# First we isolate the body of the table which contains all the information
# Then we loop through each row and find all the column values for each row
for row in soup.find("tbody").find_all('tr'):
    col = row.find_all("td")
    date = col[0].text
    Open = col[1].text
    high = col[2].text
    low = col[3].text
    close = col[4].text
    adj_close = col[5].text
    volume = col[6].text
    
    # Finally we append the data of each row to the table
    netflix_data = netflix_data.append({"Date":date, "Open":Open, "High":high, "Low":low, "Close":close, "Adj Close":adj_close, "Volume":volume}, ignore_index=True)

In [6]:
netflix_data.head()

           Date    Open    High     Low   Close       Volume Adj Close
0  Jun 01, 2021  504.01  536.13  482.14  528.21   78,560,600    528.21
1  May 01, 2021  512.65  518.95  478.54  502.81   66,927,600    502.81
2  Apr 01, 2021  529.93  563.56  499.00  513.47  111,573,300    513.47
3  Mar 01, 2021  545.57  556.99  492.85  521.66   90,183,900    521.66
4  Feb 01, 2021  536.79  566.65  518.28  538.85   61,902,300    538.85

We can also use the pandas read_html function using the url

In [7]:
read_html_pandas_data = pd.read_html(url)

Or we can convert the BeautifulSoup object to a string

In [8]:
read_html_pandas_data = pd.read_html(str(soup))

Because there is only one table on the page, we just take the first table in the list returned

In [9]:
netflix_dataframe = read_html_pandas_data[0]
netflix_dataframe.head()

           Date    Open    High     Low  Close* Adj Close**     Volume
0  Jun 01, 2021  504.01  536.13  482.14  528.21      528.21   78560600
1  May 01, 2021  512.65  518.95  478.54  502.81      502.81   66927600
2  Apr 01, 2021  529.93  563.56  499.00  513.47      513.47  111573300
3  Mar 01, 2021  545.57  556.99  492.85  521.66      521.66   90183900
4  Feb 01, 2021  536.79  566.65  518.28  538.85      538.85   61902300

Now, using BeautifulSoup we will extract past Amazon data

Use the `requests` library to download the webpage [https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0220EN-SkillsNetwork/labs/project/amazon_data_webpage.html](https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0220EN-SkillsNetwork/labs/project/amazon_data_webpage.html).

In [10]:
am= requests.get("https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0220EN-SkillsNetwork/labs/project/amazon_data_webpage.html").text

Parse the html data using `beautiful_soup`.

In [11]:
soup = BeautifulSoup(am, 'html5lib')

Content of the title attribute?

In [13]:
x=soup.find_all('title')[0].string
x

'Amazon.com, Inc. (AMZN) Stock Historical Prices & Data - Yahoo Finance'

Using beautiful soup extract the table with historical share prices and store it into a dataframe named `amazon_data`. The dataframe should have columns Date, Open, High, Low, Close, Adj Close, and Volume.

In [14]:
amazon_data = pd.DataFrame(columns=["Date", "Open", "High", "Low", "Close", "Volume"])

for row in soup.find("tbody").find_all("tr"):
    col = row.find_all("td")
    date = col[0].text
    Open = col[1].text
    high = col[2].text
    low = col[3].text
    close = col[4].text
    adj_close = col[5].text
    volume = col[6].text
    
    amazon_data = amazon_data.append({"Date":date, "Open":Open, "High":high, "Low":low, "Close":close, "Adj Close":adj_close, "Volume":volume}, ignore_index=True)

In [16]:
amazon_data.head()

           Date      Open      High       Low     Close       Volume Adj Close
0  Jan 01, 2021  3,270.00  3,363.89  3,086.00  3,206.20   71,528,900  3,206.20
1  Dec 01, 2020  3,188.50  3,350.65  3,072.82  3,256.93   77,556,200  3,256.93
2  Nov 01, 2020  3,061.74  3,366.80  2,950.12  3,168.04   90,810,500  3,168.04
3  Oct 01, 2020  3,208.00  3,496.24  3,019.00  3,036.15  116,226,100  3,036.15
4  Sep 01, 2020  3,489.58  3,552.25  2,871.00  3,148.73  115,899,300  3,148.73

Columns of the dataframe

In [17]:
amazon_data.columns

Index(['Date', 'Open', 'High', 'Low', 'Close', 'Volume', 'Adj Close'], dtype='object')

`Open` of the last row of the amazon_data dataframe?

In [18]:
amazon_data.loc[amazon_data[['Open']].size-1, 'Open']

'656.29'

In this notebook, we extracted stock data from a webpage using beautiful_soup and requests libraries. We also used the read_html function to convert the html table into a pandas dataframe. In the next Notebook, we will analyze the stock data using the pandas library